### ISSUE TITLE
timeline view on mobile web doesn't fit

### ISSUE THREAD

**Issue by benharri** [mimonelu/klearsky#32]
Home timeline is too wide for mobile web. Profile seems ok though. Can get some screenshots if that's helpful

**Comment by keita-oi** [comment]
@benharri 
Yes, I need screenshot. Can you give it me?

**Comment by benharri** [comment]
![Screenshot_20240515-220720.png](https://github.com/mimonelu/klearsky/assets/7453240/9c84ce23-4ffe-45d6-bf77-e0b6f6dc2e20)

here's the catch up feed

Firefox on Android 14. pixel 6a

**Comment by mimonelu** [comment]
Ok I could repro this bug on Android Emulator. I'll tell you again when this bug be fixed. Thanks!

![screenshot 2024-05-16 13 10 56](https://github.com/mimonelu/klearsky/assets/1230131/84b47948-e6ce-4837-b12d-7413eab053a5)

**Comment by mimonelu** [comment]
@benharri 
I think the bugs ware fixed. Can you check again?

**Comment by benharri** [comment]
yeah looks great, thanks!
